### ISSUE TITLE
[Bug]: Converting doesn't work for big.js and dynamic currencies

### ISSUE THREAD

**Issue by omergoldreich-simplex** [dinerojs/dinero.js#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

converting between currencies with dynamic currencies and big.js throws an error in dinero v2 alpha 8:
```javascript
{"level":"ERROR","message":"api error","service":"fee-calculation-service","error":{"message":"[big.js] Invalid number","stack":"Error: [big.js] Invalid number\n    at parse (/usr/src/app/node_modules/big.js/big.js:142:13)\n    at new Big (/usr/src/app/node_modules/big.js/big.js:109:9)\n    at Big.P.times.P.mul (/usr/src/app/node_modules/big.js/big.js:832:17)\n    at Object.multiply (/usr/src/app/src/components/price-breakdown/domain/pricing-calculator/dineroBigInt.ts:11:25)\n    at converter (/usr/src/app/node_modules/core/dist/esm/api/convert.js:27:26)\n    at convert (/usr/src/app/node_modules/dinero.js/src/api/convert.ts:20:10)\n    at EndUserChargeFiatCalculator.calculatePriceBreakdown (/usr/src/app/src/components/price-breakdown/domain/pricing-calculator/pricingCalculator.ts:59:59)\n    at PriceBreakdown.create (/usr/src/app/src/components/price-breakdown/domain/PriceBreakdown.ts:25:83)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at createPriceBreakdownRoute (/usr/src/app/src/components/price-breakdown/routes/price-breakdown.ts:66:29)"},"timestamp":"2021-09-14T11:47:34.451Z","meta":{"requestId":"15fb4f95-4bfb-493d-a310-9e75124e75db","correlationId":"59bb478c-fd81-424a-ba74-eb8d9b4256da","requestUrl":"POST /price-breakdown"}}```

### Expected behavior

Conversion to work without error.

### Steps to reproduce

I'm trying to convert between currencies on a setup where all currencies are dynamic and big.js is used.

```javascript

const dineroBigConverter = new DineroBigConverter(
      pricingCalculationParameters.fiatCurrency,
      pricingCalculationParameters.product.cryptoCurrency 
    );
    const simplexStaticMinimumUsd = dineroBigConverter.getUSDDinero(
      new Big(pricingCalculationParameters.simplexStaticMinimumUsd)
    );
    const simplexStaticMinimumUsdInFiatCurrencyy = convert(
      simplexStaticMinimumUsd,
      dineroBigConverter.currencyMap['fiatCurrency'],
      {fiatCurrency: new Big(pricingCalculationParameters.usdToFiatRateOffered)}
    );
```

where DineroBigConverter class definition is:
```javascript
import Big from "big.js";
import {Currency} from "dinero.js";

import {bigDinero} from "./dineroBigInt";

type dineroBigCurrency = {code: string; base: Big; exponent: Big};

export class DineroBigConverter {
  private readonly dineroFiatCurrency: dineroBigCurrency;
  private readonly dineroCryptoCurrency: dineroBigCurrency;
  private readonly fiatExponent: Big;
  private readonly fiatScale: Big;
  private readonly base: Big;
  private readonly cryptoExponent: Big;
  readonly currencyMap: {[currency: string]: Currency<Big>};
  private static readonly usdCurrency = {
    code: "USD",
    base: new Big(10),
    exponent: new Big(2)
  };
  constructor(fiatCurrency: string, cryptoCurrency: string) {
    this.fiatExponent = new Big(2);
    this.fiatScale = new Big(8);
    this.cryptoExponent = new Big(8);
    this.base = new Big(10);
    this.dineroFiatCurrency = {
      code: fiatCurrency,
      base: this.base,
      exponent: this.fiatExponent
    };
    this.dineroCryptoCurrency = {
      code: cryptoCurrency,
      base: this.base,
      exponent: this.cryptoExponent
    };
    this.currencyMap = {
      USD: DineroBigConverter.usdCurrency,
      fiatCurrency: this.dineroFiatCurrency,
      cryptoCurrency: this.dineroCryptoCurrency
    };
  }
  getFiatDinero(amount: Big) {
    return bigDinero({
      amount: amount.times(new Big(Math.pow(10, this.fiatScale.toNumber()))),
      currency: this.dineroFiatCurrency,
      scale: this.fiatScale
    });
  }
  getUSDDinero(amount: Big) {
    return bigDinero({
      amount: amount.times(new Big(Math.pow(10, this.fiatExponent.toNumber()))),
      currency: DineroBigConverter.usdCurrency
    });
  }
  getCryptoDinero(amount: Big) {
    return bigDinero({
      amount: amount.times(new Big(Math.pow(10, this.cryptoExponent.toNumber()))),
      currency: this.dineroCryptoCurrency
    });
  }
  static decimalToPercent(decimalAmount: number) {
    return {
      amount: new Big(decimalAmount).times(Math.pow(10, 4)),
      scale: new Big(2)
    };
  }
}

```

and big.js calculator definitions is as provided in docs:

```javascript
import {createDinero, Calculator, ComparisonOperator} from "dinero.js";
import Big from "big.js";

const calculator: Calculator<Big> = {
  add: (a, b) => a.plus(b),
  compare: (a, b) => (a.cmp(b) as unknown) as ComparisonOperator,
  decrement: (v) => v.minus(new Big(1)),
  increment: (v) => v.plus(new Big(1)),
  integerDivide: (a, b) => a.div(b).round(0, Big.roundDown),
  modulo: (a, b) => a.mod(b),
  multiply: (a, b) => a.times(b),
  power: (a, b) => a.pow(Number(b)),
  subtract: (a, b) => a.minus(b),
  toNumber: (v) => v.toNumber(),
  zero: () => new Big(0)
};
export const bigDinero = createDinero({calculator});

```

### Version

2.0.0-alpha.8

### Environment

Nodejs v12.20.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahdayan** [comment]
Hey @omergoldreich-simplex, could you please provide a minimal reproduction in a CodeSandbox so I can better investigate the issue?

Here's a starter: https://codesandbox.io/s/github/dinerojs/dinero.js/tree/main/examples/starter
