### ISSUE TITLE
[Bug]: Currency conversion with BigInts throws error

### ISSUE THREAD

**Issue by AustinShelby** [dinerojs/dinero.js#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```ts
import { calculator } from "@dinero.js/calculator-bigint";
import { convert, createDinero, toSnapshot } from "dinero.js";

const dinero = createDinero({ calculator });

const USD = { code: "USD", base: BigInt(10), exponent: BigInt(2) };
const EUR = { code: "USD", base: BigInt(10), exponent: BigInt(2) };

const rates = { EUR: { amount: BigInt(89), scale: BigInt(2) } };
const d = dinero({ amount: BigInt(500), currency: USD });

const c = convert(d, EUR, rates);
console.log(toSnapshot(c));
```

Following the example shown on the [documentation](https://v2.dinerojs.com/docs/api/conversions/convert#convert-to-another-currency) but with BigInts gets the following error:

```
C:\Users\Austin\Documents\Projects\dinero-test\node_modules\@dinero.js\calculator-bigint\dist\umd\index.production.js:2
!function(e,n){"object"==typeof exports&&"undefined"!=typeof module?n(exports):"function"==typeof define&&define.amd?define(["exports"],n):n((e="undefined"!=typeof globalThis?globalThis:e||self)["@dinero.js/calculator-bigint"]={})}(this,(function(e){"use strict";var n,t=function(e,n){return e+n};!function(e){e[e.LT=-1]="LT",e[e.EQ=0]="EQ",e[e.GT=1]="GT"}(n||(n={}));var r=function(e,t){return e<t?n.LT:e>t?n.GT:n.EQ},o=function(e){return e-1n},u=function(e){return e+1n},i=function(e,n){return e/n},c=function(e,n){return e%n},f=function(e,n){return e*n},d=function(e,n){return Math.pow(e,n)},a=function(e,n){return e-n},l=function(e){return Number(e)};function m(){return 0n}var p={add:t,compare:r,decrement:o,increment:u,integerDivide:i,modulo:c,multiply:f,power:d,subtract:a,toNumber:l,zero:m};e.add=t,e.calculator=p,e.compare=r,e.decrement=o,e.increment=u,e.integerDivide=i,e.modulo=c,e.multiply=f,e.power=d,e.subtract=a,e.toNumber=l,e.zero=m,Object.defineProperty(e,"__esModule",{value:!0})}));



                                                                                              ^

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at Object.f [as multiply] (C:\Users\Austin\Documents\Projects\dinero-test\node_modules\←[4m@dinero.js←[24m\calculator-bigint\dist\umd\index.production.js:2:554)
    at convertFn (C:\Users\Austin\Documents\Projects\dinero-test\node_modules\←[4mdinero.js←[24m\dist\cjs\index.development.js:715:26)
    at convert (C:\Users\Austin\Documents\Projects\dinero-test\node_modules\←[4mdinero.js←[24m\dist\cjs\index.development.js:1918:10)
    at Object.<anonymous> (C:\Users\Austin\Documents\Projects\dinero-test\main.js:10:35)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1099:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:975:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
```

### Expected behavior

Should work the same way as Numbers.

### Steps to reproduce

https://codesandbox.io/s/clever-johnson-uog8pp?file=/main.ts

### Version

2.0.0-alpha.8

### Environment

Node.js v17.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahdayan** [comment]
Hey @AustinShelby, you're using the code `"USD"` twice, this is causing the issue.

Here's an amended reproduction: https://stackblitz.com/edit/node-graxd5?file=index.mjs
