### ISSUE TITLE
[Bug]: Dinero is not a function while importing in CommonJS

### ISSUE THREAD

**Issue by utkarshdubey** [dinerojs/dinero.js#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```js
const Dinero = require("dinero.js");

const calculate_image_usage = (number_of_images) => {
  const usage = Dinero({ amount: 0.02, currency: "USD" });
  const total_usage = usage.multiply(number_of_images);
  return total_usage;
};

console.log(calculate_image_usage(5).getAmount());

module.exports = { calculate_image_usage };
```

When trying to run this on Node, it throws a weird error saying "Dinero is not a function", I've tried changing the import name and other things but it doesn't seem to work.

Here's the stack trace:
```
const usage = Dinero({ amount: 0.02, currency: "USD" });
                ^

TypeError: Dinero is not a function
    at calculate_image_usage (/home/.../utils/misc.js:4:17)
    at Object.<anonymous> (/home/.../misc.js:9:13)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

### Expected behavior

A working script.

### Steps to reproduce

1. Install dinero.js using `npm i dinero.js@alpha`
2. Run the code

### Version

latest alpha

### Environment

Node v16.19.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utkarshdubey** [comment]
I was on the v1 documentation. My bad.
