### ISSUE TITLE
Maybe issue with `multiply` and `bigint`, not sure?

### ISSUE THREAD

**Issue by acron0** [dinerojs/dinero.js#736]
It's unclear if I am doing something wrong here but I'd appreciate some guidance.

```typescript
import * as dinero from 'dinero.js'
import { calculator } from '@dinero.js/calculator-bigint'

export const GBP = {
    code: 'GBP',
    base: 10n,
    exponent: 2n,
}

const dineroBigint = dinero.createDinero({ calculator })

export const multiply = (aMoney: bigint, bScalar: number): bigint => {
    const aC = dineroBigint({ amount: aMoney, currency: GBP })
    const r = dinero.multiply(aC, bScalar)
    return dinero.toSnapshot(r).amount
}
```

produces the following error

```
TypeError: Cannot convert a BigInt value to a number
        at Math.pow (<anonymous>)

      29 |     export const multiply = (aMoney: bigint, bScalar: bigint): bigint => {
      30 |         const aC = dineroBigint({ amount: aMoney, currency: GBP })
    > 31 |         const r = dinero.multiply(aC, bScalar)
         |                          ^
      32 |         return dinero.toSnapshot(r).amount
      33 |     }
      34 |

      at Object.pow [as power] (node_modules/@dinero.js/calculator-bigint/dist/umd/index.production.js:2:586)
      at power (node_modules/dinero.js/dist/cjs/index.development.js:668:29)
      at convertScaleFn (node_modules/dinero.js/dist/cjs/index.development.js:1630:12)
      at Object.multiplyFn [as multiply] (node_modules/dinero.js/dist/cjs/index.development.js:2226:10)
```

The error message implies there is a scale conversion going on but the definition of `multiply` is 

```
function multiply<bigint>(multiplicand: dinero.Dinero<bigint>, multiplier: bigint | ScaledAmount<bigint>): dinero.Dinero<bigint>
```

indicating that the second argument is not expected to be a Dinero-wrapped `bigint`

EDIT: I also have a very similar error with `allocate`: `TypeError: Cannot convert a BigInt value to a number, at Math.pow`

**Comment by acron0** [comment]
Sorry, this is a duplicate of https://github.com/dinerojs/dinero.js/issues/677
